#---------------------------------------------------------------------------------
# Overall
#---------------------------------------------------------------------------------

package_name: brandtemplate
version: 0.1.0
authors: [aplunket <applunket@gmail.com>]

#---------------------------------------------------------------------------------
# Font
#
# If updating font then you need to copy the font files 
# into brandtemplate/template_files/font before running
#---------------------------------------------------------------------------------
font: 
  font_family: Inter
  font_type: ttf                           #can be one of ttf, otf, woff, woff2
  font_regular: Inter-Regular.ttf
  font_bold: Inter-Bold.ttf
  font_italic: Inter-Italic.ttf
  font_bolditalic: Inter-BoldItalic.ttf

#---------------------------------------------------------------------------------
# Quarto template
#
# If updating backgrounds / logo then you need to copy the files 
# into brandtemplate/template_files before running
#---------------------------------------------------------------------------------
quarto: 
  title-background: title-background.svg          #cover slide background
  section-background: section-background.svg      #new section slide background
  thank-you-background: thank-you-background.svg  #thank you slide background

  slide-background-image: true
  slide-background: background.svg        

  page-size: A4 #alternative is "letter"

  font-size-body: 1.2em
  font-line-height: 1.1em
  font-size-slide-heading: 2.4em
  font-size-slide-subheading: 2.1em
  font-size-title: 4em
  font-size-title-subtitle: 2.8em
  font-size-title-author: 2em
  font-size-section: 3.2em
  font-size-thank-you: 3.2em
  font-size-slide-number: 1em

  color-title: #ffffff
  color-subtitle: #EA4237
  color-author: #ffffff
  color-heading: #3048F3
  color-subheading: #8f8f8f
  color-section: #ffffff
  color-thank-you: #ffffff
  color-body: #131516
  color-accent: #cc0000
  color-body-background: #ffffff

  slide-number-vertical-pos: bottom
  slide-number-horizontal-pos: right

  #presentation title position
  title-top: 40%
  title-left: 15%
  title-text-align: left #center is an alternative

  #section title position
  section-top: 40%
  section-left: 15%
  section-text-align: left

  #thank you title position
  thank-you-top: 40%
  thank-you-left: 15%
  thank-you-text-align: left

  use_logo: false
  logo_file: logo.svg
  logo-max-width: 15%
  logo-max-height: 5%
  logo-vertical-pos: bottom
  logo-horizontal-pos: right

#---------------------------------------------------------------------------------
# plotnine
#---------------------------------------------------------------------------------

plotnine:
  base-font-size: 15
  title-size: 32
  subtitle-size: 20
  caption-size: 15
  base-graph-color: #36454f
  gridlines-color: #ededed
  title-color: #36454f
  subtitle-color: #5E6A72
  caption-color: #5E6A72
  legend-position: bottom
  legend-direction: horizontal
  


#---------------------------------------------------------------------------------
# great-tables
#---------------------------------------------------------------------------------

great-tables: